arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: l10n_untranslated.json
use-escaping: true
preferred-supported-locales:
  - en
  - hi
  - hi_KH
  - kn

